### ISSUE TITLE
Optimize Code

### ISSUE THREAD

**Issue by Aarijit** [zikrach/price-optimization-shiny#2]
Hi Dmytro,

Thanks for the great repo! I found it extremely useful. But I got stucked at one place. In the `function.R` code, there's a function called `optimize`. And this function has not been defined anywhere else. Can you please share this function with us?

Thanks!

**Comment by zikrach** [comment]
Hi!

I've used standard optimize function from the package stats for One Dimensional Optimization.

https://www.rdocumentation.org/packages/stats/versions/3.6.1/topics/optimize
